config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # ActiveAdmin.routes(self)

  namespace :admin do
    resources :forms do
      resources :questions, controller: 'forms/questions'
      resource :declaration, controller: 'forms/declarations', on: :edit
    end
    get 'created', to: 'created_forms#index'
  end
  get '/admin', to: 'admin/forms#index'

  resources :visa_applications do
    collection do
      get 'finished_form'
    end
  end
  resources :questions

  resources :users


  get 'landing', to:'layouts#landing'
  get 'choose_country', to:'layouts#choose_country'
  get 'country_page', to:'layouts#country_page'
  get 'country_page_2', to:'layouts#country_page_2'
  get 'country_page_3', to:'layouts#country_page_3'
  get 'country_page_4', to:'layouts#country_page_4'
  get 'account', to:'layouts#account'

  root to: "layouts#choose_country"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/visa_application_forms_controller.rb
class VisaApplicationFormsController < ApplicationController
  before_action :set_visa_application_form, only: [:show, :edit, :update, :destroy]

  # GET /visa_application_forms
  # GET /visa_application_forms.json
  def index
    @visa_application_forms = VisaApplicationForm.all
  end

  # GET /visa_application_forms/1
  # GET /visa_application_forms/1.json
  def show
  end

  # GET /visa_application_forms/new
  def new
    @visa_application_form = VisaApplicationForm.new
  end

  # GET /visa_application_forms/1/edit
  def edit
  end

  # POST /visa_application_forms
  # POST /visa_application_forms.json
  def create
    @visa_application_form = VisaApplicationForm.new(visa_application_form_params)

    respond_to do |format|
      if @visa_application_form.save
        format.html { redirect_to @visa_application_form, notice: 'Visa application form was successfully created.' }
        format.json { render :show, status: :created, location: @visa_application_form }
      else
        format.html { render :new }
        format.json { render json: @visa_application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /visa_application_forms/1
  # PATCH/PUT /visa_application_forms/1.json
  def update
    respond_to do |format|
      if @visa_application_form.update(visa_application_form_params)
        format.html { redirect_to @visa_application_form, notice: 'Visa application form was successfully updated.' }
        format.json { render :show, status: :ok, location: @visa_application_form }
      else
        format.html { render :edit }
        format.json { render json: @visa_application_form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /visa_application_forms/1
  # DELETE /visa_application_forms/1.json
  def destroy
    @visa_application_form.destroy
    respond_to do |format|
      format.html { redirect_to visa_application_forms_url, notice: 'Visa application form was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_visa_application_form
      @visa_application_form = VisaApplicationForm.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def visa_application_form_params
      params.require(:visa_application_form).permit(:country_id, :title)
    end
end

app/helpers/visa_application_forms_helper.rb
module VisaApplicationFormsHelper
end

app/views/visa_application_forms/_form.html.erb
<%= form_with(model: visa_application_form, local: true) do |form| %>
  <% if visa_application_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(visa_application_form.errors.count, "error") %> prohibited this visa_application_form from being saved:</h2>

      <ul>
      <% visa_application_form.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :country_id %>
    <%= form.number_field :country_id %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/visa_application_forms/edit.html.erb
<h1>Editing Visa Application Form</h1>

<%= render 'form', visa_application_form: @visa_application_form %>

<%= link_to 'Show', @visa_application_form %> |
<%= link_to 'Back', visa_application_forms_path %>

app/views/visa_application_forms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Visa Application Forms</h1>

<table>
  <thead>
    <tr>
      <th>Country</th>
      <th>Title</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @visa_application_forms.each do |visa_application_form| %>
      <tr>
        <td><%= visa_application_form.country_id %></td>
        <td><%= visa_application_form.title %></td>
        <td><%= link_to 'Show', visa_application_form %></td>
        <td><%= link_to 'Edit', edit_visa_application_form_path(visa_application_form) %></td>
        <td><%= link_to 'Destroy', visa_application_form, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Visa Application Form', new_visa_application_form_path %>

app/views/visa_application_forms/new.html.erb
<h1>New Visa Application Form</h1>

<%= render 'form', visa_application_form: @visa_application_form %>

<%= link_to 'Back', visa_application_forms_path %>

app/views/visa_application_forms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Country:</strong>
  <%= @visa_application_form.country_id %>
</p>

<p>
  <strong>Title:</strong>
  <%= @visa_application_form.title %>
</p>

<%= link_to 'Edit', edit_visa_application_form_path(@visa_application_form) %> |
<%= link_to 'Back', visa_application_forms_path %>