config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # ActiveAdmin.routes(self)

  namespace :admin do
    resources :forms do
      resources :questions, controller: 'forms/questions'
      resource :declaration, controller: 'forms/declarations', on: :edit
    end
    get 'created', to: 'created_forms#index'
  end
  get '/admin', to: 'admin/forms#index'

  resources :visa_applications do
    collection do
      get 'finished_form'
    end
  end
  resources :questions

  resources :users


  get 'landing', to:'layouts#landing'
  get 'choose_country', to:'layouts#choose_country'
  get 'country_page', to:'layouts#country_page'
  get 'country_page_2', to:'layouts#country_page_2'
  get 'country_page_3', to:'layouts#country_page_3'
  get 'country_page_4', to:'layouts#country_page_4'
  get 'account', to:'layouts#account'

  root to: "layouts#choose_country"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/admin/forms/declarations_controller.rb
class Admin::Forms::DeclarationsController < Admin::BaseController
  before_action :set_form
  before_action :set_declaration, only: [:show, :edit, :update, :destroy]


  # GET /forms/1/declarations/1
  # GET /forms/1/declarations/1.json
  def show
  end

  # GET /forms/1/declarations/new
  def new
    @declaration = Declaration.new
    @declaration.form = @form
  end

  # GET /forms/1/declarations/1/edit
  def edit
  end

  # POST /forms/1/declarations
  # POST /forms/1/declarations.json
  def create
    # @declaration = @form.declaration.new(declaration_params)
    @declaration = Declaration.new(declaration_params)
    @declaration.form_id = params[:form_id]

    respond_to do |format|
      if @declaration.save
        format.html { redirect_to admin_form_questions_path(@form), notice: 'Вопрос успешно создан' }
        format.json { render :show, status: :created, location: @declaration }
      else
        format.html { render :new }
        format.json { render json: @declaration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1/declarations/1
  # PATCH/PUT /forms/1/declarations/1.json
  def update
    respond_to do |format|
      if @declaration.update(declaration_params)
        format.html { redirect_to admin_form_questions_path(@form), notice: 'Вопрос успешно обновлен' }
        format.json { render :show, status: :ok, location: @declaration }
      else
        format.html { render :edit }
        format.json { render json: @declaration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1/declarations/1
  # DELETE /forms/1/declarations/1.json
  def destroy
    @declaration.destroy
    respond_to do |format|
      format.html { redirect_to admin_form_questions_path(@form), notice: 'Вопрос успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:form_id])
    end

    def set_declaration
      @declaration = @form.declaration
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def declaration_params
      params.require(:declaration).permit(
        :title,
        :body,
        :step,
        )
    end
end

app/controllers/admin/forms/questions_controller.rb
class Admin::Forms::QuestionsController < Admin::BaseController
  before_action :set_form
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /forms/1/questions
  # GET /forms/1/questions.json
  def index
    @questions = @form.questions.all.order('step, ordering')
  end


  # GET /forms/1/questions/1
  # GET /forms/1/questions/1.json
  def show
  end

  # GET /forms/1/questions/new
  def new
    @question = @form.questions.new
    @question.question_type = Question::STRING_INPUT
    @question.answers.build(answer: 'Да')
    @question.answers.build(answer: 'Нет')
  end

  # GET /forms/1/questions/1/edit
  def edit
  end

  # POST /forms/1/questions
  # POST /forms/1/questions.json
  def create
    filtered_params = filter_params(question_params)
    @question = @form.questions.new(filtered_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to admin_form_questions_path, notice: 'Вопрос успешно создан' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1/questions/1
  # PATCH/PUT /forms/1/questions/1.json
  def update
    filtered_params = filter_params(question_params)

    respond_to do |format|
      if @question.update(filtered_params)
        format.html { redirect_to admin_form_questions_path, notice: 'Вопрос успешно обновлен' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1/questions/1
  # DELETE /forms/1/questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to admin_form_questions_path, notice: 'Вопрос успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:form_id])
    end

    def set_question
      @question = @form.questions.find(params[:id])
    end

    def filter_params(p)
      filtered = p
      if filtered[:question_type] == Question::STRING_INPUT || filtered[:DATE] == Question::DATE
        p.delete(:answers)
      end

      filtered[:placeholder] = '' if filtered[:DATE] == Question::DATE
      filtered
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(
        :title,
        :question_type,
        :created_at,
        :updated_at,
        :muted_text,
        :placeholder,
        :step,
        :ordering,
        :form_id,
        :has_optional_answer,
        :is_group_view,
        answers_attributes: [:answer, :_destroy, :id]
        )
    end
end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < Admin::BaseController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end


  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to admin_forms_path, notice: 'Виза успешно создана' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to admin_forms_path, notice: 'Виза успешно обновлена' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to admin_forms_path, notice: 'Виза успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:title, :description)
    end
end

app/helpers/admin/forms_helper.rb
module Admin::FormsHelper
end

app/views/admin/forms/_form.html.erb
<%= form_with model: [:admin, @form], remote: true do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title, 'Введите название визы', class: 'control-label' %>
        <%= f.text_field :title, placeholder: 'Введите название визы', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :description, 'Введите описание визы', class: 'control-label' %>
        <%= f.text_field :description, placeholder: 'Введите описание визы', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.submit @form.new_record? ? "Создать визу" : "Сохранить визу", class: 'btn btn-primary' %>
        <% unless @form.new_record? %>
          <%= link_to 'Удалить визу', admin_form_path(@form),
            data: { :confirm => 'Вы уверенеы?' }, :method => :delete, class: 'btn btn-outline-danger' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/forms/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Все визы', admin_forms_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Редактирование визы</li>
  </ol>
</nav>

<h1>Редактирование визы</h1>
<br><br>

<%= render 'form' %>

app/views/admin/forms/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item active" aria-current="page">Все визы</li>
  </ol>
</nav>

<h1>Созданные визы</h1>
<br><br>

<% @forms.each do |form| %>
  <h3><%= link_to form.title, edit_admin_form_path(form) %></h3>
<% end %>

<br><br>
<%= link_to 'Создать новую визу', new_admin_form_path, class: 'btn btn-primary'%>

app/views/admin/forms/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Все визы', admin_forms_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Создание визы</li>
  </ol>
</nav>

<h1>Создание новой визы</h1>
<br><br>

<%= render 'form' %>