config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admins
  # ActiveAdmin.routes(self)

  namespace :admin do
    resources :forms do
      resources :questions, controller: 'forms/questions'
      resource :declaration, controller: 'forms/declarations', on: :edit
    end
    get 'created', to: 'created_forms#index'
  end
  get '/admin', to: 'admin/forms#index'

  resources :visa_applications do
    collection do
      get 'finished_form'
    end
  end
  resources :questions

  resources :users


  get 'landing', to:'layouts#landing'
  get 'choose_country', to:'layouts#choose_country'
  get 'country_page', to:'layouts#country_page'
  get 'country_page_2', to:'layouts#country_page_2'
  get 'country_page_3', to:'layouts#country_page_3'
  get 'country_page_4', to:'layouts#country_page_4'
  get 'account', to:'layouts#account'

  root to: "layouts#choose_country"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/question.rb
class Question < ApplicationRecord

  STRING_INPUT = "string_input"
  DATE = "date"
  RADIOBUTTON_CHOICE = "radiobutton_choice"
  RADIOBUTTON_CHOICE_WITH_INPUT = "radiobutton_choice_with_input"

  QUESTION_TYPES = [STRING_INPUT, DATE, RADIOBUTTON_CHOICE, RADIOBUTTON_CHOICE_WITH_INPUT]
  QUESTION_TYPE_CHOICE = [
    ["String input", STRING_INPUT],
    ["Date", DATE],
    ["Radiobutton choice", RADIOBUTTON_CHOICE],
    ["Radiobutton choice with input", RADIOBUTTON_CHOICE_WITH_INPUT]
  ]

  QUESTION_TYPE_CHOICE_RU = [
    ["Обычное поле", STRING_INPUT],
    ["Дата", DATE],
    ["Радиокнопка", RADIOBUTTON_CHOICE],
    ["Радиокнопка c доп. полем", RADIOBUTTON_CHOICE_WITH_INPUT]
  ]

  has_many :question_options, dependent: :destroy
  has_many :answers, dependent: :destroy
  accepts_nested_attributes_for :answers, allow_destroy: true

  belongs_to :form

  validates :title, presence: true
  validates :question_type, presence: true
end

app/controllers/admin/forms/declarations_controller.rb
class Admin::Forms::DeclarationsController < Admin::BaseController
  before_action :set_form
  before_action :set_declaration, only: [:show, :edit, :update, :destroy]


  # GET /forms/1/declarations/1
  # GET /forms/1/declarations/1.json
  def show
  end

  # GET /forms/1/declarations/new
  def new
    @declaration = Declaration.new
    @declaration.form = @form
  end

  # GET /forms/1/declarations/1/edit
  def edit
  end

  # POST /forms/1/declarations
  # POST /forms/1/declarations.json
  def create
    # @declaration = @form.declaration.new(declaration_params)
    @declaration = Declaration.new(declaration_params)
    @declaration.form_id = params[:form_id]

    respond_to do |format|
      if @declaration.save
        format.html { redirect_to admin_form_questions_path(@form), notice: 'Вопрос успешно создан' }
        format.json { render :show, status: :created, location: @declaration }
      else
        format.html { render :new }
        format.json { render json: @declaration.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1/declarations/1
  # PATCH/PUT /forms/1/declarations/1.json
  def update
    respond_to do |format|
      if @declaration.update(declaration_params)
        format.html { redirect_to admin_form_questions_path(@form), notice: 'Вопрос успешно обновлен' }
        format.json { render :show, status: :ok, location: @declaration }
      else
        format.html { render :edit }
        format.json { render json: @declaration.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1/declarations/1
  # DELETE /forms/1/declarations/1.json
  def destroy
    @declaration.destroy
    respond_to do |format|
      format.html { redirect_to admin_form_questions_path(@form), notice: 'Вопрос успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:form_id])
    end

    def set_declaration
      @declaration = @form.declaration
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def declaration_params
      params.require(:declaration).permit(
        :title,
        :body,
        :step,
        )
    end
end

app/controllers/admin/forms/questions_controller.rb
class Admin::Forms::QuestionsController < Admin::BaseController
  before_action :set_form
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /forms/1/questions
  # GET /forms/1/questions.json
  def index
    @questions = @form.questions.all.order('step, ordering')
  end


  # GET /forms/1/questions/1
  # GET /forms/1/questions/1.json
  def show
  end

  # GET /forms/1/questions/new
  def new
    @question = @form.questions.new
    @question.question_type = Question::STRING_INPUT
    @question.answers.build(answer: 'Да')
    @question.answers.build(answer: 'Нет')
  end

  # GET /forms/1/questions/1/edit
  def edit
  end

  # POST /forms/1/questions
  # POST /forms/1/questions.json
  def create
    filtered_params = filter_params(question_params)
    @question = @form.questions.new(filtered_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to admin_form_questions_path, notice: 'Вопрос успешно создан' }
        format.json { render :show, status: :created, location: @question }
      else
        format.html { render :new }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1/questions/1
  # PATCH/PUT /forms/1/questions/1.json
  def update
    filtered_params = filter_params(question_params)

    respond_to do |format|
      if @question.update(filtered_params)
        format.html { redirect_to admin_form_questions_path, notice: 'Вопрос успешно обновлен' }
        format.json { render :show, status: :ok, location: @question }
      else
        format.html { render :edit }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1/questions/1
  # DELETE /forms/1/questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to admin_form_questions_path, notice: 'Вопрос успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:form_id])
    end

    def set_question
      @question = @form.questions.find(params[:id])
    end

    def filter_params(p)
      filtered = p
      if filtered[:question_type] == Question::STRING_INPUT || filtered[:DATE] == Question::DATE
        p.delete(:answers)
      end

      filtered[:placeholder] = '' if filtered[:DATE] == Question::DATE
      filtered
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(
        :title,
        :question_type,
        :created_at,
        :updated_at,
        :muted_text,
        :placeholder,
        :step,
        :ordering,
        :form_id,
        :has_optional_answer,
        :is_group_view,
        answers_attributes: [:answer, :_destroy, :id]
        )
    end
end

app/controllers/admin/forms_controller.rb
class Admin::FormsController < Admin::BaseController
  before_action :set_form, only: [:show, :edit, :update, :destroy]

  # GET /forms
  # GET /forms.json
  def index
    @forms = Form.all
  end


  # GET /forms/1
  # GET /forms/1.json
  def show
  end

  # GET /forms/new
  def new
    @form = Form.new
  end

  # GET /forms/1/edit
  def edit
  end

  # POST /forms
  # POST /forms.json
  def create
    @form = Form.new(form_params)

    respond_to do |format|
      if @form.save
        format.html { redirect_to admin_forms_path, notice: 'Виза успешно создана' }
        format.json { render :show, status: :created, location: @form }
      else
        format.html { render :new }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forms/1
  # PATCH/PUT /forms/1.json
  def update
    respond_to do |format|
      if @form.update(form_params)
        format.html { redirect_to admin_forms_path, notice: 'Виза успешно обновлена' }
        format.json { render :show, status: :ok, location: @form }
      else
        format.html { render :edit }
        format.json { render json: @form.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forms/1
  # DELETE /forms/1.json
  def destroy
    @form.destroy
    respond_to do |format|
      format.html { redirect_to admin_forms_path, notice: 'Виза успешно удалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form
      @form = Form.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_params
      params.require(:form).permit(:title, :description)
    end
end

app/helpers/admin/forms_helper.rb
module Admin::FormsHelper
end

app/views/admin/forms/questions/_form.html.erb
<%= form_with model: [:admin, @question.form, @question] do |f| %>
  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.label :question_type, 'Выберите тип вопроса', class: 'control-label' %>
        <div>
          <% Question::QUESTION_TYPE_CHOICE_RU.each do |val| %>
            <label style="float: left; padding-right: 30px">
              <%= f.radio_button :question_type, val[1] %> <%= val[0] %>
            </label>
          <% end %>
          <div style="float: none; clear: both"></div>
        </div>
      </div>
    </div>
  </div>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title, 'Введите вопрос', class: 'control-label' %>
        <%= f.text_field :title, placeholder: 'Введите вопрос', class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :muted_text, 'Введите описание вопроса', class: 'control-label' %>
        <%= f.text_field :muted_text, placeholder: 'Введите описание вопроса', class: 'form-control' %>
      </div>
      <div id="form-placeholder" class="form-group hide">
        <%= f.label :placeholder, 'Введите текст плейсхолдера', class: 'control-label' %>
        <%= f.text_field :placeholder, placeholder: 'Введите текст плейсхолдера', class: 'form-control' %>
      </div>

      <div id="form-radio-options" class="form-group">
        <%= f.label :answers, 'Добавьте варианты ответов для радиокнопки', class: 'control-label hide' %>
        <div>
          <%= f.nested_fields_for :answers do |ff| %>
            <div style='width: 120px; display: inline-block; margin-right: 10px;'>
              <%= ff.text_field :answer, class: 'form-control', style: 'width: 60px; display: inline-block; margin-right: 0;' %>
              <%= ff.remove_nested_fields_link 'x', class: 'btn btn-outline-danger', role: 'button', style: "display: inline-block; width: 40px;" %>
            </div>
          <% end %>
          <%= f.add_nested_fields_link :answers, '+', class: 'btn btn-outline-primary', role: 'button', style: "width: 40px;" %>
        </div>
      </div>
    </div>
  </div>
  <%# <%= @question.answers.inspect %>
  <div class="row">
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :step, 'Номер страницы', class: 'control-label' %>
        <%= f.select :step, (1..10).to_a, {}, {class: 'form-control', style: 'width: 60px; display: inline-block; margin-left: 10px;'} %>
      </div>
    </div>
    <div class="col-md-4">
      <div class="form-group">
        <%= f.label :ordering, 'Номер вопроса', class: 'control-label' %>
        <%= f.select :ordering, (1..10).to_a, {}, {class: 'form-control', style: 'width: 60px; display: inline-block; margin-left: 10px;'} %>
      </div>
    </div>
  </div>

  <div class="row">
    <div class="col-md-12">
      <div class="form-group">
        <%= f.submit @question.new_record? ? "Создать вопрос" : "Сохранить вопрос", class: 'btn btn-primary' %>
        <% unless @question.new_record? %>
          <%= link_to 'Удалить вопрос', admin_form_question_path(@question.form, @question),
            data: { :confirm => 'Вы уверенеы?' }, :method => :delete, class: 'btn btn-outline-danger' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/forms/questions/_question.html.erb
<div style="padding-bottom: 20px">
  <div class="row">
    <div class="col-md-6">
      <h3 style="display: inline"><%= question.title %></h3>
      <span class="text-muted "><%= question.placeholder.blank? ? '' : "(#{question.placeholder})" %></span>
      <%= link_to '[редактировать]', edit_admin_form_question_path(question.form, question), style: "font-size: 12px; " %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <% case question.question_type %>
      <% when Question::STRING_INPUT %>
        <input class="form-control" type="text" value="">
      <% when Question::DATE %>
        <input class="form-control" type="date" value="">
      <% when Question::RADIOBUTTON_CHOICE %>
        <div style="margin: 10px 0 30px;">
          <% question.answers.each do |answer| %>
            <label style="margin-right: 20px;"><input type="radio">&nbsp;&nbsp;<%= answer.answer %></label>
          <% end %>
        </div>
      <% when Question::RADIOBUTTON_CHOICE_WITH_INPUT %>
        <div style="margin: 10px 0 30px;">
          <% question.answers.each do |answer| %>
            <label style="margin-right: 20px;"><input type="radio">&nbsp;&nbsp;<%= answer.answer %></label>
          <% end %>
          <br>
          <input class="form-control" type="text" value="">
        </div>

      <% end %>

    </div>
  </div>
</div>

app/views/admin/forms/questions/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Все визы', admin_forms_path %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Редактирование визы', '/admin/created' %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to @form.title, admin_form_questions_path(@form) %></li>
    <li class="breadcrumb-item active" aria-current="page">Редактирование вопроса</li>
  </ol>
</nav>

<h1>Редактирование вопроса</h1>
<br><br>

<%= render 'form' %>

app/views/admin/forms/questions/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Все визы', admin_forms_path %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Редактирование визы', '/admin/created' %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @form.title %></li>
  </ol>
</nav>

<h1><%= @form.title %></h1>
<br><br>

<% if @questions.present? %>
  <% @questions.each do |question| %>
    <%= render 'question', question: question %>
  <% end %>
  <hr>
<% else %>
  <p><i>Еще нет вопросов</i></p>
  <br>
<% end %>

<br>
<%= link_to 'Добавить вопрос', new_admin_form_question_path(@form), class: 'btn btn-primary'%>

<% unless @form.declaration.present? %>
  <%= link_to 'Добавить декларацию', new_admin_form_declaration_path(@form), class: 'btn btn-outline-primary'%>
<% else %>
  <%= link_to 'Редактировать декларацию', edit_admin_form_declaration_path(@form), class: 'btn btn-outline-primary'%>
<% end %>

app/views/admin/forms/questions/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Все визы', admin_forms_path %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to 'Редактирование визы', '/admin/created' %></li>
    <li class="breadcrumb-item" aria-current="page"><%= link_to @form.title, admin_form_questions_path(@form) %></li>
    <li class="breadcrumb-item active" aria-current="page">Новый вопрос</li>
  </ol>
</nav>

<h1>Добавление вопроса</h1>
<br><br>

<%= render 'form' %>